spring:
  application:
    name: spendwise
  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASS}
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
security:
  jwt:
    # 1h in millisecond
    expiration-time: 3600000