--liquibase formatted sql
--changeset LD:create-user-table failOnError:true
CREATE TABLE USERS (
    USER_ID NUMERIC(10) PRIMARY KEY,
    DISPLAY_NAME VARCHAR(100) NOT NULL,
    EMAIL_ID VARCHAR(255) UNIQUE,
    MOBILE_NUMBER VARCHAR(10) UNIQUE
);
CREATE SEQUENCE USERS_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 1;